# Generated by Django 5.0.3 on 2024-03-16 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='fee',
            new_name='fees',
        ),
    ]
